ci: deactivate e2e (#115)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,58 +26,59 @@ jobs:
         run: |
           npm run format:check
           npm run lint
-  test:
-    needs: check
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-26.04, macos-26, windows-2025]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v7
-      - name: Setup node
-        uses: actions/setup-node@v7
-        with:
-          node-version: 26
-      - name: Set Playwright cache path
-        shell: bash
-        run: |
-          if [ ${{ runner.os }} == Linux ]; then
-            echo "PLAYWRIGHT_CACHE_PATH=~/.cache/ms-playwright" >> $GITHUB_ENV
-          elif [ ${{ runner.os }} == macOS ]; then
-            echo "PLAYWRIGHT_CACHE_PATH=~/Library/Caches/ms-playwright" >> $GITHUB_ENV
-          elif [ ${{ runner.os }} == Windows ]; then
-            echo "PLAYWRIGHT_CACHE_PATH=C:\Users\runneradmin\AppData\Local\ms-playwright" >> $GITHUB_ENV
-          else
-            echo "OS not found. Exiting." && exit 1
-          fi
-      - name: Cache dependencies
-        id: cache
-        uses: actions/cache@v6
-        with:
-          path: |
-            node_modules
-            ${{ env.PLAYWRIGHT_CACHE_PATH }}
-          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
-      - name: Install dependencies
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: npm ci
-      - name: Install Playwright browsers and browser deps
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: npx playwright install --with-deps chromium chrome msedge
-      - name: Run e2e tests
-        run: npm run test:headless
-      - name: Upload test report
-        uses: actions/upload-artifact@v7
-        if: success() || failure()
-        with:
-          name: playwright-report
-          path: playwright-report
-      - name: Upload coverage report
-        if: runner.os == 'Linux'
-        uses: codecov/codecov-action@v6
-        with:
-          fail_ci_if_error: true
-          files: test-results/coverage/result/coverage.json
-          token: ${{ secrets.CODECOV_TOKEN }}
+  # Deactivated because of https://github.com/elias-pap/youtube-share-clip/issues/86#issue-2476546617. Tests can be run locally.
+  # test:
+  #   needs: check
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-26.04, macos-26, windows-2025]
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v7
+  #     - name: Setup node
+  #       uses: actions/setup-node@v7
+  #       with:
+  #         node-version: 26
+  #     - name: Set Playwright cache path
+  #       shell: bash
+  #       run: |
+  #         if [ ${{ runner.os }} == Linux ]; then
+  #           echo "PLAYWRIGHT_CACHE_PATH=~/.cache/ms-playwright" >> $GITHUB_ENV
+  #         elif [ ${{ runner.os }} == macOS ]; then
+  #           echo "PLAYWRIGHT_CACHE_PATH=~/Library/Caches/ms-playwright" >> $GITHUB_ENV
+  #         elif [ ${{ runner.os }} == Windows ]; then
+  #           echo "PLAYWRIGHT_CACHE_PATH=C:\Users\runneradmin\AppData\Local\ms-playwright" >> $GITHUB_ENV
+  #         else
+  #           echo "OS not found. Exiting." && exit 1
+  #         fi
+  #     - name: Cache dependencies
+  #       id: cache
+  #       uses: actions/cache@v6
+  #       with:
+  #         path: |
+  #           node_modules
+  #           ${{ env.PLAYWRIGHT_CACHE_PATH }}
+  #         key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
+  #     - name: Install dependencies
+  #       if: steps.cache.outputs.cache-hit != 'true'
+  #       run: npm ci
+  #     - name: Install Playwright browsers and browser deps
+  #       if: steps.cache.outputs.cache-hit != 'true'
+  #       run: npx playwright install --with-deps chromium chrome msedge
+  #     - name: Run e2e tests
+  #       run: npm run test:headless
+  #     - name: Upload test report
+  #       uses: actions/upload-artifact@v7
+  #       if: success() || failure()
+  #       with:
+  #         name: playwright-report
+  #         path: playwright-report
+  #     - name: Upload coverage report
+  #       if: runner.os == 'Linux'
+  #       uses: codecov/codecov-action@v6
+  #       with:
+  #         fail_ci_if_error: true
+  #         files: test-results/coverage/result/coverage.json
+  #         token: ${{ secrets.CODECOV_TOKEN }}
